# NUMPY
**faster computations**

**faster than a list**

**tensor is faster than numpy**



In [2]:
#In Python we have lists that serve the purpose of arrays, but they are slow to process.

#NumPy aims to provide an array object that is up to 50x faster than traditional Python lists
#Arrays are very frequently used in data science, where speed and resources are very important
#Arrays are very frequently used in data science, where speed and resources are very important

#Why is NumPy Faster Than Lists?
#NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

#This behavior is called locality of reference in computer science.

#This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.
#Which Language is NumPy written in?
#NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.

In [3]:
!pip install numpy
#2 types
#use the library based upon requirement
#undertand the entire library-documentation
#pip install <libraryname> -- (pypi <module>)

Defaulting to user installation because normal site-packages is not writeable


In [4]:
import numpy as np  #as----alias
print(np.__version__)

1.26.4


In [5]:
#comparison between list and a numpy array
import time

In [6]:
#different dimension array
#in order to know whether it is a numpy aray or not
normal_list=[1,2,3,4]
numpy_arr=np.array([1,2,3,4])
print(type(normal_list))
print(type(numpy_arr))


<class 'list'>
<class 'numpy.ndarray'>


In [7]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#shape
#ndim
#1D,2D,3D

numpy_arr1=np.array([1])
numpy_arr2=np.array([[1,2,3]])
numpy_arr3=np.array([[[1,2,3]]])

print(numpy_arr1.shape)#1D==>only one element
print(numpy_arr2.shape)#2D==>(x,y)
print(numpy_arr3.shape)#3D==>(x,y,z)

print(np.ndim(numpy_arr1))#1D
print(np.ndim(numpy_arr2))#2D
print(np.ndim(numpy_arr3))#3D




(1,)
(1, 3)
(1, 1, 3)
1
2
3


In [9]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)#0D
print(b.ndim)#1D
print(c.ndim)#2D
print(d.ndim)#3D

0
1
2
3


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [11]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[1, 1])
arr[1][1]

2nd element on 1st row:  7


7

In [12]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])
print(arr[0, 1, 1])
print(arr[1,1,1])

6
5
11


In [13]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])
arr[0,-3]

Last element from 2nd dim:  10


3

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]


In [15]:
a=np.array([[[1,2,3,7],[4,5,6,11],[7,8,9,10]]])
print(a)
print(a.shape)

[[[ 1  2  3  7]
  [ 4  5  6 11]
  [ 7  8  9 10]]]
(1, 3, 4)


# slicing

In [17]:
#slicing
n=np.array([1,2,3,4])
n[0:2]



array([1, 2])

In [18]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])
arr[2:4]

array([20, 25])

In [19]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])

print(arr[::2])

[10 20 30 40]


# datatypes

In [21]:
#datatypes
'''
i = integer
b= boolean
u= unsigned integer
f= float
c= complex float
m= timedelta
M= datetime
O= object
S= string
'''

'\ni = integer\nb= boolean\nu= unsigned integer\nf= float\nc= complex float\nm= timedelta\nM= datetime\nO= object\nS= string\n'

In [22]:
#to print datatype
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int32


In [23]:
arr = np.array([1, 2, 3, 4], dtype="S")
arr.dtype
arr


array([b'1', b'2', b'3', b'4'], dtype='|S1')

# datatype conversion

In [25]:
#converting float to int
arr = np.array([1.1, 2.1, 3.1])
print(arr.dtype)
newarr = arr.astype('i')
newarr

float64


array([1, 2, 3], dtype=int32)

# copy

In [27]:
#copy()-copy is a new array
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x

array([1, 2, 3, 4, 5])

# view

In [29]:
#view-the view is just a view of the original array
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x


array([1, 2, 3, 4, 5])

# shape

In [31]:
#shape
arr = np.array([1, 2, 3, 4, 5])

print(arr.shape)

(5,)


In [32]:
#creating ndimensional array-maximum limit of creating an array is 32(ndim=32)
#here ndim =2 (2 dimensional array)
my = np.array([1, 2, 3], ndmin=2)
my.shape
my

array([[1, 2, 3]])

In [33]:
#creating a 3d
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])


In [34]:
#change dimension-reshape-1D to 2D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])

newarr = arr.reshape(2, 6)
newarr


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [35]:
#reshape-2D to 1D
arr = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

newarr = arr.reshape(-1)
newarr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [36]:
# Reshape the 3D array to a 2D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
array_2d = array_3d.reshape(-1, array_3d.shape[-1])
print(array_2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
#conctenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
arr

array([1, 2, 3, 4, 5, 6])

In [282]:
arr = np.arange(27)
arr
arr.shape

(27,)

In [284]:
np.transpose(arr)
arr.shape

(27,)

In [276]:
print(arr.reshape(9,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]
 [24 25 26]]


In [268]:
arr.reshape(9,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [270]:
arr.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# flatten

In [249]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.flatten()
x[0]=55
print(x)
print(arr)

[55  2  3  4  5]
[1 2 3 4 5]


In [251]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.ravel()
x[0]=55
print(x)
print(arr)

[55  2  3  4  5]
[55  2  3  4  5]


# sort

In [39]:
#sort-where
arr = np.array([1, 2, 3, 4, 5, 4, 4])

print(np.where(arr == 4))


(array([3, 5, 6], dtype=int64),)


**comparison between numpy and list**

In [41]:
#using list
import time
start_time=time.time()
lst=list(range(100000))
for i in range(100000):
    lst[i]*=lst[i]
end_time=time.time()
print(f"Execution time:{end_time-start_time}seconds")

Execution time:0.03221750259399414seconds


In [42]:
#using numpy-faster computations comare to list
import time
start_time=time.time()
arr=np.arange(100000)
arr=arr*arr;
end_time=time.time()
print(f"Execution time:{end_time-start_time}seconds")

Execution time:0.0seconds


In [43]:
arr = np.array([1, 2, 3], ndmin=5)
arr.shape
arr

array([[[[[1, 2, 3]]]]])

In [44]:
arr = np.array([[1, 2, 3],[4,5,6]])
print(arr.shape)
print(arr[0])
arr[0][1]=23  #updating the 1 index value of 0 with 23
arr

(2, 3)
[1 2 3]


array([[ 1, 23,  3],
       [ 4,  5,  6]])

In [45]:
f=np.array([[[1,2,3,4],[4,5,6,7]]])
f2=np.array([[[1,2,3,4],[4,5,6,7]]])
f3=np.concatenate((f,f2),axis=0)
print(f3.shape ) #(2=no. of elements,2=no. of rows,4=no. of columns)
print(f3)

(2, 2, 4)
[[[1 2 3 4]
  [4 5 6 7]]

 [[1 2 3 4]
  [4 5 6 7]]]


> **numpy-creating array**

# zeros

In [48]:
#1.zeros-default value it takes as float
a=np.zeros((2,2,2))
a

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [49]:
#1.zeros-here we defining the datatatype as integer
a=np.zeros((2,2,2),dtype="i")
a

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int32)

# ones

In [51]:
a=np.ones((2,2,2))
a

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [52]:
a=np.ones((2,2,2),dtype="int8")
a

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int8)

# range

In [54]:
a=np.arange(1,20,5)
a

array([ 1,  6, 11, 16])

# linspace
#print number of sample we want to print from given range

#maximum length is 50

In [56]:
a=np.linspace(1,20,50) #1=start ,20=end ,50=no.of sampls
a

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

# full

In [58]:
a=np.full((2,2,3),fill_value=5)  #it is fillinf every value with given value 5
a

array([[[5, 5, 5],
        [5, 5, 5]],

       [[5, 5, 5],
        [5, 5, 5]]])

# eye

In [60]:
a=np.eye(2,3) #identity matrix
a

array([[1., 0., 0.],
       [0., 1., 0.]])

In [61]:
#a=np.ones((2,2,2),dtype="int8")
a=np.eye(2,3)#identity matrix
a

array([[1., 0., 0.],
       [0., 1., 0.]])

# diag

In [63]:
a=np.diag((2,3))
a

array([[2, 0],
       [0, 3]])

In [64]:
a=np.diag((1,2,3,4,5))
a


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# random.random

In [66]:
a=np.random.random((3,3)) #float values between 0 and 1 (standard deviation)
a

array([[0.70109062, 0.23392373, 0.762957  ],
       [0.88724539, 0.12514179, 0.59196178],
       [0.15613429, 0.43668269, 0.93882548]])

# randint

In [68]:
a=np.random.randint(100) #random number in the range of 100
print(a)

41


In [69]:
from numpy import random   #5 random numbers in between 1 and 100
x=random.randint(100, size=(5))
print(x)


[44 60 66 85  9]


In [ ]:
#random integers between 0 to 100 with 3 rows and 5 columns --2D
x = random.randint(100, size=(3, 5))
print(x)

In [94]:
#update 2D array -you have to add it based on row and column
x = random.randint(100, size=(3, 3))
x=np.append(x,[[99,88,11]],axis=0)
x


array([[51, 50, 77],
       [40, 18, 61],
       [25, 56, 12],
       [99, 88, 11]])

In [158]:
x = random.randint(100, size=(3,3))
np.append(x,[[99,23,12],[1,33,67],[4,1,2]],axis=0)

array([[59, 13, 28],
       [39,  4, 58],
       [67, 81, 55],
       [99, 23, 12],
       [ 1, 33, 67],
       [ 4,  1,  2]])

In [ ]:
a=np.random.randint((1,20,5)) #random numbers between 1 and excluding 20
print(a)

In [190]:
x = random.randint(100, size=(3,3,3))
x=np.append(x,[[99,44,11]],axis=0)
x

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

# rand

In [ ]:
#1D array containing 5 random floats 
x = random.rand(5)
print(x)

In [ ]:
from numpy import random #float number between 0 and 1
x = random.rand()
print(x)


In [ ]:
#2-D array with 3 rows and 5 columns containing random numbers 0 and 1
x = random.rand(3, 5)
print(x)

In [ ]:
np.random.rand(5,5) #between 0 and 1

# choice

In [ ]:
#method allows you to generate  a random value based on array of values
x = random.choice([3, 5, 7, 9])
print(x)

In [ ]:
#method allows you to generate  a random values from array consisting of 3 rows and 5 columns
x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

In [ ]:
#specifies the probability of occuring each element
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(10))
print(x)

In [ ]:
#specifies the probability of occuring each element with size of 3 rows and 5 columns
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

# shuffle

In [ ]:
#The shuffle() method makes changes to the original array.
arr = np.array([1, 2, 3, 4, 5])
print(random.shuffle(arr))
print(arr)

# permutation

In [ ]:
#The permutation() method returns a re-arranged array (and leaves the original array un-changed).

arr = np.array([1, 2, 3, 4, 5])
print(random.permutation(arr))
arr

In [ ]:
np.random.randn(5,5) 

In [ ]:
np.random.uniform(1,5,size=(5,5))

# slicing

In [ ]:
s=np.random.randint(5,100,size=(10,10)) 
print(s[0])
s[0][2:4]

In [ ]:
my_table=np.random.randint(10,40,size=(10,10))
print(my_table)


In [ ]:
#print(my_table[:][4])

In [ ]:
my_=np.random.randint(10,40,size=(10,10))
print(my_)

In [ ]:
print(my_[7:,7:])  #last 3 row and  3 columns

# Boolean indexing

In [ ]:
a=[1,2,3,4]
for i in range(0,len(a)):
      a[i]=a[i]*4
print(a)

In [ ]:
w=np.array([1,2,3,4])
w=w*4
print(w)

# filter

In [ ]:
A=np.array([1,2,3,4,11])
print(A<10)
print(A[A<10])
A[A<10]

In [ ]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
a=np.arange(50,100,5)
print(a)
b=a[a>70]
b

In [ ]:
b[0]=400
b

In [ ]:
b[b<89]=99
b

In [ ]:
b[b==99]=11
b

In [ ]:
b[b<89]=b[b==99]=1000
b

In [ ]:
#append,insertion'
#append=add element at the end of the array
#insertion=add the element at a specified index
y=[1,2,3,4,5]
z=np.append(y,1)
z


In [ ]:
#insertion
np.insert(z,obj=4,values=22)

In [ ]:
a=[1,2,3]
b=[4,5,6]
c=zip(a,b)
print(list(c))

In [ ]:
a = ("John", "Charles", "Mike")
b = ("Jenny", "Christy", "Monica")

x = zip(a, b)
print(tuple(x))

# sqrt

In [289]:
A=np.random.uniform(1,10,(2,2))
A

array([[5.67692896, 8.34555031],
       [2.26019204, 9.74332053]])

In [305]:
np.sqrt(A)

array([[2.38263068, 2.88886661],
       [1.50339351, 3.12142925]])

In [327]:
a=frozenset([1,2,3])
b=frozenset([1,2,2,3])
x=list(zip(a,b))
x

[(1, 1), (2, 2), (3, 3)]

In [331]:
18.5**2/3

114.08333333333333

In [337]:
4.8**2/2

11.52

In [1]:
7+8+32+43+92+64

246

In [3]:
246/6

41.0

In [27]:
7-41

-34

In [13]:
64-41

23

In [21]:
23**2

529

In [23]:
1156+1089+81+4+529+2601

5460

In [25]:
5460/5

1092.0

In [43]:
1092**0.5

33.04542328371661

In [31]:
(1213302.25)**0.5

1101.5

In [41]:
#variance
import numpy as np
n=np.array([7,8,32,43,64,92])
np.var(n)

910.0

In [45]:
#standard deviation
import numpy as np
n=np.array([7,8,32,43,64,92])
np.std(n)

30.166206257996713

In [69]:
#correlation coefficient
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([3,4,5,6,7])
c=np.array([93,42,102,111,99])
print(np.corrcoef([a,b]))

[[1. 1.]
 [1. 1.]]


In [71]:
print(np.corrcoef([a,c]))

[[1.       0.469441]
 [0.469441 1.      ]]
