In [9]:
#creating ndimensional array
import numpy as np
m=int(input("enter rows"))
n=int(input("enter columns"))
matrix=np.ndarray(shape=(m,n),dtype=int)
print("enter %d elements of %dx%d"%((m*n),m,n))
for i in range(m):
    for j in range(n):
        matrix[i][j]=int(input())
print("%dx%d matrix is"%(m,n))
print(matrix)

enter rows 3
enter columns 3


enter 9 elements of 3x3


 1
 2
 2
 3
 4
 5
 6
 7
 8


3x3 matrix is
[[1 2 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
matrix=np.random.choice(100,size=(3,3))
matrix

In [ ]:
import numpy as np
matrix=np.random.randint(100,size=(5,5))
matrix.ndim

In [ ]:
n=np.random.randint(100,size=(2,3))
n.ndim

In [ ]:
def fun(n,char):
    for i in n:
        if i in a:
            n=n.replace(i,char)
    print(n)
fun("the ravartau","#")

In [ ]:
#innomatice===in...in..innomatics?

In [ ]:
def fun(n):
    for i in n:
        a=((n[:2]+"...")*2)+n[:]+"?"
    print(a)
fun("innomatics")

In [ ]:
n=np.array([[1,2,3],[4,5,6]])
for row in n:
    for i in row:
        print(i,end=" ")
    print()

In [ ]:
n=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
for row in n:
        print(row)

In [ ]:
n=np.random.randint(100,size=(10,10))
n

In [ ]:
n[7:11,7:10]

In [ ]:
n[3:6,4:7]

In [ ]:
s=np.array([[1,2,3],[4,5,6],[7,8,9]])
s

In [ ]:
print(s[1,2])

In [ ]:
print(s[1:3,1:3])

In [ ]:
print(s[1,2])

In [ ]:
print(s[1:3,0:2])

In [ ]:
s=np.array([1,2,3,4,5,6],ndmin=32)
s.ndim
print(s)

In [57]:
#creating multidimensional array
import numpy as np
y=int(input("enter number of rows"))
z=int(input("enter number of col"))
x=int(input("enter the dimension"))
p=np.ndarray(shape=(x,y,z),dtype=int)
print("enter %d elements in %dx%dx%d"%((x*y*z),x,y,z))
for i in range(x):
    for j in range(y):
      for k in range(z):
        p[i][j][k]=int(input())
print("the %dx%dx%d matrix is"%(x,y,z))
print(p)

enter number of rows 1
enter number of col 2
enter the dimension 4


enter 8 elements in 4x1x2


 1
 2
 3
 4
 5
 6
 7
 8


the 4x1x2 matrix is
[[[1 2]]

 [[3 4]]

 [[5 6]]

 [[7 8]]]


In [55]:
print("enter %d elements in %dx%dx%d"%((x*y*z),x,y,z))
print("the %dx%dx%d matrix is"%(x,y,z))

enter 18 elements in 3x2x3
the 3x2x3 matrix is


In [19]:
#creating 1 dimensional array
m=int(input("enter size"))
arr=np.ndarray(shape=(m),dtype=int)
for i in range(m):
    arr[i]=int(input())
print(arr)
    

enter size 5
 1
 2
 3
 4
 5


[1 2 3 4 5]


In [89]:
#Creating a simple array in numpy
lst=['a','b','c','c',5.3]
arr=np.array(lst)
print(type(arr))
print(arr.size)
print(arr.itemsize)#returns the size (in bytes) of each element of a NumPy array.
print("NUmpy Array:",arr)  #ndarray is nothing but n dimentional array.

NameError: name 'a' is not defined

In [111]:
n=np.array([1,2,3,4])
print(n)
print(n**2)

[1 2 3 4]
[ 1  4  9 16]


In [109]:
n=[1,2,3,4,5]
n**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

# priority for dtypes

In [7]:
#1st priority for strings
import numpy as np
b=np.array([1,3.3,'ayesh'])
print(b)

['1' '3.3' 'ayesh']


In [9]:
##2nd priority for complex
b=np.array([1,3.3,1+5j])
print(b)

[1. +0.j 3.3+0.j 1. +5.j]


In [11]:
##3rd priority for float
b=np.array([1,3.3])
print(b)

[1.  3.3]


In [13]:
##4th priority for int
b=np.array([1,3])
print(b)

[1 3]


# itemsize

In [25]:
b=np.array([1,3])
print(b.dtype)
b.itemsize

int32


4

In [27]:
b=np.array([1,'two',3.3,4+4j])#range of numpy is 
print(b.dtype)
b.itemsize

<U64


256

# arange

In [64]:

n=np.arange(2,9,2)
print(n)
n[0]

[2 4 6 8]


2

In [52]:
n=np.arange(1,10).reshape(3,3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# indexing

In [67]:
#2D
n=np.arange(1,10).reshape(3,3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
n[0]

array([1, 2, 3])

In [56]:
n[0][0]

1

In [58]:
n[0,0]

1

In [62]:
print(n[1:3,1:3])

[[5 6]
 [8 9]]


In [73]:
#3D
a=np.arange(1,28).reshape(3,3,3)
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [75]:
a[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
a[0][0]

array([1, 2, 3])

In [79]:
a[0,0]

array([1, 2, 3])

In [81]:
a[0,1,2]

6

In [83]:
a[0,1:3,1:3]

array([[5, 6],
       [8, 9]])

In [85]:
a[0:3,1:3,1:3]

array([[[ 5,  6],
        [ 8,  9]],

       [[14, 15],
        [17, 18]],

       [[23, 24],
        [26, 27]]])

In [23]:
s=np.arange(1,10).reshape(3,3)
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
for i,j in np.ndenumerate(s):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
(2, 0) 7
(2, 1) 8
(2, 2) 9


In [149]:
s[0:2:1]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
s[2:3:3]

array([[7, 8, 9]])

In [15]:
import numpy as np
n=np.arange(9).reshape(3,3)
for i in np.nditer(n):
    print(i)

0
1
2
3
4
5
6
7
8


In [19]:
n=np.arange(9).reshape(3,3)
for i,j in np.ndenumerate(n):
    print(i,j)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [37]:
a=np.arange(10).reshape(10,)
for i in np.nditer(a):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [45]:
b=np.arange(27).reshape(3,3,3)
for i in np.nditer(b):
    print(i)
 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [55]:
#print everyelement
print(b)
b=np.arange(27).reshape(3,3,3)
for i in np.nditer(b,order="c",flags=["external_loop"]):
    print(i)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [57]:
#print column wise
b=np.arange(27).reshape(3,3,3)
for i in np.nditer(b,order="f",flags=["external_loop"]):
    print(i)

[ 0  9 18]
[ 3 12 21]
[ 6 15 24]
[ 1 10 19]
[ 4 13 22]
[ 7 16 25]
[ 2 11 20]
[ 5 14 23]
[ 8 17 26]


In [67]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [69]:
d

array([[0, 1, 2],
       [3, 4, 5]])

In [63]:
c=np.arange(6).reshape(2,3)
d=np.arange(6).reshape(2,3)
np.vstack([c,d])

array([[0, 1, 2],
       [3, 4, 5],
       [0, 1, 2],
       [3, 4, 5]])

In [65]:
c=np.arange(6).reshape(2,3)
d=np.arange(6).reshape(2,3)
np.hstack([c,d])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [71]:
c=np.arange(6).reshape(2,3)
d=np.arange(6).reshape(2,3)
np.column_stack([c,d])

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

# numpy maths

In [155]:
w=np.array([1,2,3])
print(w+3)

[4 5 6]


In [157]:
y=w+3
print(y)
print(w)

[4 5 6]
[1 2 3]


In [165]:
x=w=np.array([1,2,3])
y=x*3
print(y)
print(x)

[3 6 9]
[1 2 3]


In [169]:
bool(1^10)

True

# numpy logical

In [410]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,19]])
np.logical_and(a,b)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,19]])
np.logical_or(a,b)

In [173]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,19]])
np.logical_or(a,b)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [175]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,19]])
np.logical_xor(a,b)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [177]:
np.logical_not(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# ways to access an element

In [5]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
a[0][0],a[1,1],a[2,2]=66,77,88
amn 

array([[66,  2,  3],
       [ 4, 77,  6],
       [ 7,  8, 88]])

In [29]:
a[[0,1,2],[0,1,2]]=100,99,88
a

array([[100,   2,   3],
       [  4,  99,   6],
       [  7,   8,  88]])

# random in numpy

In [37]:
x=np.random.randn()
x

-0.12444446843877366

In [105]:
y=np.random.randn(2,3)
y

array([[-0.02841172, -0.43992513, -1.31019792],
       [ 1.4224826 , -1.51626843,  1.60717384]])

In [61]:
a=np.random.randint(99)
a

4

In [83]:
a=np.random.randint(2,5)
a

3

In [69]:
a=np.random.randint(1,5,size=(3,3))
a

array([[3, 4, 3],
       [2, 1, 3],
       [4, 4, 1]])

In [111]:
a=np.random.uniform(10,size=(2,2))
a

array([[2.79620091, 2.06988737],
       [7.74385702, 6.02061386]])

In [129]:
a=np.random.uniform(20,40,size=(2,2))
a

array([[39.28574226, 39.18444536],
       [20.54068888, 30.66219714]])

In [135]:
arr=np.random.randint(100, size=(5,))
print(arr)
arr[4]

[18 48 65 72 57]


57

In [155]:
a=np.random.randint(10,size=(3,3))
b=np.random.randint(10,size=(3,3))
print(a)
print(b)

[[3 1 3]
 [3 2 0]
 [0 2 0]]
[[5 7 2]
 [0 4 9]
 [1 9 1]]


In [157]:
a+b

array([[ 8,  8,  5],
       [ 3,  6,  9],
       [ 1, 11,  1]])

In [159]:
np.add(a,b)

array([[ 8,  8,  5],
       [ 3,  6,  9],
       [ 1, 11,  1]])

In [161]:
a-b

array([[-2, -6,  1],
       [ 3, -2, -9],
       [-1, -7, -1]])

In [163]:
np.subtract(a,b)

array([[-2, -6,  1],
       [ 3, -2, -9],
       [-1, -7, -1]])

In [173]:
x = np.array([[1,2],[3,4]])
np.sum(x)

10

In [167]:
np.min(x)

1

In [169]:
np.min(x,axis=0)

array([1, 2])

In [171]:
np.min(x,axis=1)

array([1, 3])

# nditer,ndenumerate

In [7]:
import numpy as np
n=np.array([[1,2,3],[4,5,6]])
for i in n:
    print(i)


[1 2 3]
[4 5 6]


In [105]:
n=np.array([[1,2,3],[4,5,6]])
for i in n:
    for j in i:
     print(j)
    

1
2
3
4
5
6


In [107]:
for i in np.nditer(n):
    print(i)

1
2
3
4
5
6


In [109]:
for i,j in np.ndenumerate(n):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [121]:
for i in np.nditer(n,flags=['buffered'],op_dtypes=["S"]):
    print(i)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'


In [ ]:
for i,j in np.ndenumerate(n):
    print(i,j)

In [45]:
n

array([[1, 2, 3],
       [4, 5, 6]])

In [41]:
n=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(n,order='F',flags=['external_loop']):
    print(i)

[1 4]
[2 5]
[3 6]


In [43]:
n=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(n,order='C',flags=['external_loop']):
    print(i)

[1 2 3 4 5 6]


In [93]:
n=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(n,order="F",flags=['external_loop']):
    print(i)

[1 4]
[2 5]
[3 6]


In [97]:
for i in np.nditer(n,order="C",flags=['external_loop']):
    print(i)

[1 2 3 4 5 6]


In [101]:
c=np.array([[1,2,3],[4,5,6]])
for i in np.nditer(c,op_flags=["readwrite"]):
    i[...] = i*i

In [103]:
c

array([[ 1,  4,  9],
       [16, 25, 36]])

# copy vs view

In [131]:
#copy-the changes made in the copy array will not  affect the original array
arr=np.array([1,2,3,4,5])
arr1=arr.copy()
arr1[2]=55
print(arr)
print(arr1)



[1 2 3 4 5]
[ 1  2 55  4  5]


In [129]:
#view-the changes made in the view array will affect the original array
arr=np.array([1,2,3,4,5])
arr1=arr.view()
arr1[2]=55
print(arr)
print(arr1)

[ 1  2 55  4  5]
[ 1  2 55  4  5]


# flatten  vs ravel

In [139]:
#flatten
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1=arr.flatten()
arr1[2]=55
print(arr)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 1  2 55  4  5  6  7  8  9 10]


In [141]:
#ravel
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1=arr.ravel()
arr1[2]=55
print(arr)
print(arr1)

[[ 1  2 55  4  5]
 [ 6  7  8  9 10]]
[ 1  2 55  4  5  6  7  8  9 10]


In [145]:
#flatten
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr.flatten()
arr[0]=55
print(arr)
#print(arr1)

[[55 55 55 55 55]
 [ 6  7  8  9 10]]


# permutation vs shuffle

In [153]:
#shuffle
from numpy import random
arr = np.array([1, 2, 3, 4, 5])

arr1=random.shuffle(arr)

print(arr)
print(arr1)


[4 2 3 1 5]
None


In [155]:
#permutation
from numpy import random
arr = np.array([1, 2, 3, 4, 5])

arr1=random.permutation(arr)

print(arr)
print(arr1)

[1 2 3 4 5]
[3 1 4 2 5]


# insert

In [165]:
#insert
arr=np.array([[ 0,1,2],[ 3 , 4 , 5],[ 6 , 7  ,8]])
a=np.insert(arr,obj=2,values=55)
print(a)
print(arr)

[ 0  1 55  2  3  4  5  6  7  8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# append

In [169]:
#append
arr=np.array([[ 0,1,2],[ 3 , 4 , 5],[ 6 , 7  ,8]])
a=np.append(arr,values=55)
print(a)
print(arr)

[ 0  1  2  3  4  5  6  7  8 55]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# concatenate

In [183]:
#concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr=np.concatenate((arr1, arr2))
print(arr1)
print(arr2)
print(arr)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


In [185]:
arr=np.concatenate(arr1, arr2)

TypeError: only integer scalar arrays can be converted to a scalar index

# sort

In [193]:
#sort
import numpy as np
arr = np.array([3, 2, 0, 1])
arr1=np.sort(arr)
print(arr1)
print(arr)

[0 1 2 3]
[3 2 0 1]


# split

In [195]:
#split
import numpy as np

array1 = np.array( [[1, 2], [3, 4], [5, 6]] )

# split into 3 arrays
splitArrays = np.split(array1, 3)

print(splitArrays)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [203]:
arr=np.array([1,2])
np.split(arr,2)

[array([1]), array([2])]

In [211]:
#split array using indices
import numpy as np

array1 = np.array( [1, 2, 3, 4, 5, 6] )

# indices at which array is split
splitIndices = [2, 5,8]

# split into subarrays 
splitArrays = np.split(array1, splitIndices)

print(splitArrays)

[array([1, 2]), array([3, 4, 5]), array([6]), array([], dtype=int32)]


In [217]:
import numpy as np

# create a 3D array
array1 = np.array([[1, 2],[3, 4]])

# split the array column-wise (axis = 0 by default)
splitArrays = np.split(array1, 2)

print("\nSplit array column-wise:")
print(splitArrays)

# split the array row-wise
splitArrays = np.split(array1, 2, axis = 1)

print("Split array row-wise:")
print(splitArrays)


Split array column-wise:
[array([[1, 2]]), array([[3, 4]])]
Split array row-wise:
[array([[1],
       [3]]), array([[2],
       [4]])]


In [219]:
#split array into uneven subarrays
import numpy as np

array1 = np.array( [[1, 2], [3, 4], [5, 6]] )

# split into 2 arrays
splitArrays = np.split(array1, 2)

print(splitArrays)

ValueError: array split does not result in an equal division

In [221]:
#split array into uneven subarrays--we can use array_split
import numpy as np
array1 = np.array( [[1, 2], [3, 4], [5, 6]] )
# split into 2 arrays
splitArrays = np.array_split(array1, 2)
print(splitArrays)

[array([[1, 2],
       [3, 4]]), array([[5, 6]])]


In [227]:
#hsplit
array1 = np.array([[1, 2],[3, 4]])
np.hsplit(array1,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

In [320]:
np.hsplit(F,[4])

[array([[1, 2],
        [3, 4]]),
 array([], shape=(2, 0), dtype=int32)]

In [332]:
np.hsplit(F,[2,4])

[array([[1, 2],
        [3, 4]]),
 array([], shape=(2, 0), dtype=int32),
 array([], shape=(2, 0), dtype=int32)]

In [336]:
F = np.array( [[1, 2], [3, 4]] )
np.hsplit(F,2)

[array([[1],
        [3]]),
 array([[2],
        [4]])]

#value error
np.hsplit(F,3)
np.hsplit(F,3)[0]
np.hsplit(F,3)[1]


In [255]:
np.hsplit(F,2)[0]

array([[1],
       [3]])

In [257]:
np.hsplit(F,2)[1]

array([[2],
       [4]])

In [293]:
np.hsplit(F,[1,9])

[array([[1],
        [3]]),
 array([[2],
        [4]]),
 array([], shape=(2, 0), dtype=int32)]

In [265]:
np.vsplit(F,2)

[array([[1, 2]]), array([[3, 4]])]

In [347]:
#error
#np.vsplit(F,3)


In [269]:
np.vsplit(F,2)[0]

array([[1, 2]])

In [273]:
np.vsplit(F,2)[1]

array([[3, 4]])

In [344]:
np.vsplit(F,[2,4])

[array([[1, 2],
        [3, 4]]),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32)]

# flat

In [357]:
#flat
a = np.arange(2, 8).reshape(3, 2)
a

array([[2, 3],
       [4, 5],
       [6, 7]])

In [349]:
a.flat[4]

4

In [351]:
a.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 55])

In [353]:
a.T.flat[4]

4

In [355]:
type(a.flat)

numpy.flatiter

# unique

In [372]:
#finding unique elements
np.unique([0,1,2,0,2,3,4,3,0,4])


array([0, 1, 2, 3, 4])

In [370]:
#Finding unique elements in a 2D array using numpy.unique()
import numpy as np
x = np.array([[1, 1], [2,3], [3,4]])
np.unique(x)


array([1, 2, 3, 4])

In [433]:
#mapping an array using numpy.unique()
import numpy as np
x = np.array([0, 1, 2, 5, 2, 6, 5, 2, 3, 1])
print(indices)
x[indices]


[0 1 4 2 3 1 2 1 4 3]


array([0, 1, 2, 2, 5, 1, 2, 1, 2, 5])

In [374]:
# Finding unique elements and their indices in a numpy array
#Mapping original values using unique and inverse index in numpy
import numpy as np
x = np.array(['o', 'p', 'y', 't', 'h', 'o', 'p'])
u, indices = np.unique(x, return_index=True)
print(u)
print(indices)
x[indices]


['h' 'o' 'p' 't' 'y']
[4 0 1 3 2]


array(['h', 'o', 'p', 't', 'y'], dtype='<U1')

In [385]:
 #Finding unique values and their indices using  numpy.unique() function with return_inverse parameter
import numpy as np
x = np.array([0, 1, 2, 5, 2, 6, 5, 2, 3, 1])
u, indices = np.unique(x, return_inverse=True)
print(u)
print(indices)

[0 1 2 3 5 6]
[0 1 2 4 2 5 4 2 3 1]


# stack

In [458]:
arr=np.stack([1,2,3,4,5,6])
np.stack(arr)

array([1, 2, 3, 4, 5, 6])

In [474]:
arr = np.array( [[5, 6,7], [6,7,8]] )
arr

array([[5, 6, 7],
       [6, 7, 8]])

In [476]:
np.stack(arr)

array([[5, 6, 7],
       [6, 7, 8]])

In [478]:
np.vstack(arr)

array([[5, 6, 7],
       [6, 7, 8]])

In [480]:
np.hstack(arr)

array([5, 6, 7, 6, 7, 8])

In [482]:
np.dstack(arr)

array([[[5, 6],
        [6, 7],
        [7, 8]]])

In [484]:
np.column_stack(arr)

array([[5, 6],
       [6, 7],
       [7, 8]])

In [464]:
np.row_stack(arr)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [470]:
arr = np.array( [[5, 6,7], [6,7,8]] )
np.stack(arr,axis=1)

array([[5, 6],
       [6, 7],
       [7, 8]])

In [472]:
arr = np.array( [[5, 6,7], [6,7,8]] )
np.stack(arr,axis=0)

array([[5, 6, 7],
       [6, 7, 8]])