### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [1]:
import numpy as np

#####1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [47]:
arr1=np.zeros(10)
print("An array of 10 zeros:")
print(arr1)
arr2=np.ones(10)
print("An array of 10 ones:")
print(arr2)
arr3=np.full(10,fill_value=5,dtype=float)
print("An array of 10 fives")
print(arr3)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
### code here

In [ ]:
## sample output

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#####2.  Write a NumPy program to create an array of the integers from 30 to 70.

In [55]:
arr_range=np.arange(30,71)
print("Array of the integers from 30 to70")
print(arr_range)

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [ ]:
### code here

In [ ]:
### sample output

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


######3. Write a NumPy program to create an array of all the even integers from 10 to 50.

In [57]:
arr_even=np.arange(10,50,2)
print("Array of all the even integers from 10 to 50")
print(arr_even)

Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [ ]:
### code here

In [ ]:
## sample output


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


######4. Write a NumPy program to create a 3x3 identity matrix.

In [63]:
identity_matrix=np.eye(3,3)
print("3x3 matrix:")
print(identity_matrix)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
### code here

In [ ]:
## sample output

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### 5. Write a NumPy program to generate a random number between 0 and 1

In [85]:
random_num=np.random.rand(1)
print("Random number between 0 and 1:")
print(random_num)

Random number between 0 and 1:
[0.12221724]


In [75]:
### code here

In [ ]:
## sample output

Random number between 0 and 1:
[0.40400053]


###### 6. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [95]:
arr_random=np.random.randn(1,15)
print("15 random numbers from a standard normal distribution:")
print(arr_random)

15 random numbers from a standard normal distribution:
[[ 0.29764347  1.58228446  0.60369997  0.25754539  1.16738453 -0.3775499
   0.40059602  0.41579445 -0.38195866  0.84068739 -0.36949425  0.45745773
  -0.93663197 -0.08874058 -1.7222497 ]]


In [ ]:
## code here

In [ ]:
## sample output

15 random numbers from a standard normal distribution:
[ 0.68439314  1.50916987 -0.75364839  0.1038106   0.07789927 -0.15349755
  1.78151615  0.49989426  0.18791322 -1.51931266 -0.55512066  2.02808972
  0.37648568  0.57999878 -0.31095957]


###### 7. Write a NumPy program to create a 3X4 array using and iterate over it.

In [105]:
arr_3d=np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])
print("Original array:")
print(arr_3d)
print("Each element of the array is:")
for i in np.nditer(arr_3d):
    print(i,end=" ")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

In [ ]:
## code here

In [ ]:
## sample output

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
10 11 12 13 14 15 16 17 18 19 20 21 

###### 8. Write a NumPy program to multiply the values ​​of two given vectors.

In [113]:
vector_1=np.array([1,8,3,5])
vector_2=np.array([10,1,4,10])
print("vector-1")
print(vector_1)
print("vector-2")
print(vector_2)
print("Multiply the values of two said vectors:")
print(vector_1*vector_2)

vector-1
[1 8 3 5]
vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


In [ ]:
## code here

In [ ]:
## sample output

Vector-1
[1 8 3 5]
Vector-2
[10  1  4 10]
Multiply the values of two said vectors:
[10  8 12 50]


###### 9. Write a NumPy program to reverse an array (first element becomes last).

In [133]:
#method-1
rev_arr=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])
print("Original array:")
print(rev_arr)
print("Reverse array:")
print(np.flip(rev_arr))

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [179]:
#method-2
rev_arr=np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37])
print("Original array:")
print(rev_arr)
print("Reverse array:")
print(rev_arr[-1::-1])

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [ ]:
### code here

In [1]:
## sample output

Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


##### 10. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.

In [187]:
arr_diag=np.diag((1,2,3,4,5))
print("5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5:")
print(arr_diag)

5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [ ]:
## code here

In [ ]:
## sample output

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


###### 11. Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array.

In [199]:
arr_sum=np.array([[0,1],[2,3]])
print("Original array:")
print(arr_sum)
print("Sum of all elements:")
print(arr_sum.sum())
print("Sum of each column:")
print(arr_sum.sum(axis=0))
print("Sum of each row:")
print(arr_sum.sum(axis=1))

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


In [ ]:
## code here

In [ ]:
## sample output

Original array:
[[0 1]
 [2 3]]
Sum of all elements:
6
Sum of each column:
[2 4]
Sum of each row:
[1 5]


###### 12. Write a NumPy program to compute the inner product of two given vectors.

In [211]:
mat_1=np.array([4,5])
mat_2=np.array([7,10])
#method-1
print("Inner product of said vectors:")
print(np.matmul(mat_1,mat_2))

Inner product of said vectors:
78


In [213]:
#method-2
print(np.dot(mat_1,mat_2))

78


In [223]:
#method-3
print(mat_1@mat_2)

78


In [ ]:
## code here 

In [ ]:
## sample output

Original vectors:
[4 5]
[ 7 10]
Inner product of said vectors:
78
