### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

In [4]:
import numpy as np

###### 1. Write a NumPy program to find the missing data in a given array.

In [6]:
arr_miss=np.array([[3,2,0,1],[1,10,12,12],[5,0,1,0]],dtype="float")
print("Original_array:")
print(arr_miss)
print()
print("missing data of the array:")
print(np.logical_not(arr_miss))

Original_array:
[[ 3.  2.  0.  1.]
 [ 1. 10. 12. 12.]
 [ 5.  0.  1.  0.]]

missing data of the array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


In [7]:
### code here

In [8]:
## sample output

##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [10]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[6,7,8],[9,10,11]])
arr3=np.array([[1,2,3],[4,5,6]])
print(arr1==arr2)

[[False False False]
 [False False False]]


In [11]:
print(arr1==arr3)

[[ True  True  True]
 [ True  True  True]]


In [12]:
### code here 

###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [14]:
rand_arr=np.random.randint(0,15,size=(4,4))
print("Original array:")
print(rand_arr)
print()
for i in np.nditer(rand_arr,order="F",flags=["external_loop"],op_flags=["readwrite"]):
       i[0],i[3]=i[3],i[0]
print(rand_arr)


Original array:
[[ 2 12  5  4]
 [14 14 14  2]
 [13 12  4  8]
 [13 14  6  7]]

[[13 14  6  7]
 [14 14 14  2]
 [13 12  4  8]
 [ 2 12  5  4]]


In [15]:
## code here

In [16]:
## sample output

###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [18]:
#convert list into array
list1=[1,2,3,4,5,6,7,8,9,10]
arr1=np.array(list1)
print(arr1)
arr1.reshape(5,2)


[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [19]:
#convert tuple into array
tuple1=(1,2,3,4,5,6,7,8,9,10)
arr1=np.array(tuple1)
print(arr1)
arr1.reshape(5,2)

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [20]:
#### code here

###### 5. Write a NumPy program to find common values between two arrays.

In [22]:
### code here

In [23]:
set1={1,2,3,4,5}
set2={5,6,7,8,9,10}
arr=np.array(set1&set2)
print(arr)
type(arr)

{5}


numpy.ndarray

###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [25]:
original_arr=np.array([[1,2],[3,4],[5,6]])
print("Reshape 3x2:")
print(original_arr)
print("Reshape 2x3:")
print(original_arr.reshape(2,3))

Reshape 3x2:
[[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
[[1 2 3]
 [4 5 6]]


In [26]:
### code here

In [27]:
### sample output

###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [130]:
original_arr=np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print("Original array:")
print(original_arr)
u,counts=np.unique(original_arr,return_counts=True)
print()
print("Frequency of unique values of the said array:")
np.array([u,counts])



Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]

Frequency of unique values of the said array:


array([[10, 20, 30, 40, 50],
       [ 3,  4,  2,  2,  1]], dtype=int64)

In [30]:
### code here

In [31]:
## sample output

###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [33]:
p=np.array([[0,0,0],[1,2,3],[4,5,6]])
q=np.array([10,11,12])
print("Original arrays")
print("array-1")
print(p)
print()
print("array-2")
print(q)
print()
print("new_array:")
print(np.add(p,q))

Original arrays
array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]

array-2
[10 11 12]

new_array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


In [34]:
### code here

In [35]:
## sample output

###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [37]:
### code here

In [38]:
#method-1
arr=np.arange(0,16).reshape(4,4)
print(arr[1])

[4 5 6 7]


In [39]:
#method-2
sec=[]
for i in np.nditer(arr,order="F",flags=["external_loop"]):
    sec.append(i[1])
print(np.array(sec))

[4 5 6 7]


In [40]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [42]:
a=np.arange(0,16).reshape(4,4)
print("Original array")
print(a)
print()
print("Extracted data: Third and fourth elements of the first and second rows")
print(a[0:2,2:4])

Original array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows
[[2 3]
 [6 7]]


In [43]:
## code here

In [44]:
## sample output


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [128]:

# for yesterday
yesterday = np.datetime64('Today')-np.timedelta64(1) 
print("yesterday:",yesterday) 

#Today
Today = np.datetime64('Today') 
print("Today:", today) 
  
  
# tomorrow
Tomorrow= np.datetime64('Today') + np.timedelta64(1)   
print("Tomorrow:",Tomorrow) 


yesterday: 2024-08-31
Today: 2024-09-01
Tomorrow: 2024-09-02


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [124]:
## code here
import numpy as np
print("First Monday in May 2017:")
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon')) 

First Monday in May 2017:
2017-05-01


In [49]:
## sample output