# Task-18 NUMPY

In [3]:
import numpy as np

**Q1.** 
**a. Create a 1D array using arange().**

   **- Use the flip() function to reverse the order of elements in a 1D array.**
   
   **- Achieve the same above output without using flip().**

In [33]:
arr_1D=np.arange(5)
print(arr_1D)
print("arr_1D with flip():",np.flip(arr_1D))
print("arr_1D without flip():",arr_1D[::-1])

[0 1 2 3 4]
arr_1D with flip(): [4 3 2 1 0]
arr_1D without flip(): [4 3 2 1 0]


**b.**

**- Create a boolean array indicating which elements of the above 1D array are greater than 3.**

**- Replace all even numbers in the array with -1**

In [352]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr)
print()
print(arr>3)
print()
print("***Replacing all even numbers in the array with -1 using boolean indexing**")
arr[arr%2==0]=-1
print(arr)


[1 2 3 4 5 6 7 8]

[False False False  True  True  True  True  True]

***Replacing all even numbers in the array with -1 usig oolean indexing**
[ 1 -1  3 -1  5 -1  7 -1]


In [356]:
print()
print("***Replacing all even numbers in the array with -1 using where function**")
np.where(arr%2==0,"-1",arr)


***Replacing all even numbers in the array with -1 using where function**


array(['1', '-1', '3', '-1', '5', '-1', '7', '-1'], dtype='<U11')

**Q2.a. Generate a 2D array with random elements.** 

   **- Transpose the array.**
   
   **- Flatten the array**

In [388]:
arr_2d=np.arange(9).reshape(3,3)
print(arr_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [390]:
print(arr_2d.transpose())

[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [392]:
print(arr_2d.flatten())

[0 1 2 3 4 5 6 7 8]


**b.**

**- Include a value of 99 at index 2 in the above array.**
    
**- Add a value of 100 to the end of a given array.**
    
**- Delete the element at index 3 from the array.**

In [395]:
#Include a value of 99 at index 2 in the above array by boolean indexing
print(arr_2d)
arr_2d[[0],[2]]=22
arr_2d

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  1, 22],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [411]:
#replacing with insert-but it will convert the into 1D-array
print(arr_2d)
a=np.insert(arr_2d,obj=2,values=55)
a

[[ 0  1 22]
 [ 3  4  5]
 [ 6  7  8]]


array([ 0,  1, 55, 22,  3,  4,  5,  6,  7,  8])

In [431]:
##Add a value of 100 to the end of a given array.-using boolean indexing
print(arr_2d)
print()
arr_2d[[2],[2]]=100
arr_2d

[[  0   1  22]
 [  3   4   5]
 [  6   7 100]]



array([[  0,   1,  22],
       [  3,   4,   5],
       [  6,   7, 100]])

In [413]:
#Add a value of 100 to the end of a given array.-converts into 1D array
print(arr_2d)
b=np.append(arr_2d,100)
b

[[ 0  1 22]
 [ 3  4  5]
 [ 6  7  8]]


array([  0,   1,  22,   3,   4,   5,   6,   7,   8, 100])

In [493]:
#It is only removing element in the 1D array
arr=np.array([1,2,3,4,5,6,7,8,9,10])
indexarray=[0,1,2,4,5,6,7,8,9]
arr=arr[indexarray]
arr

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

In [561]:
#removing element by using delete method
print(arr_2d)
c=np.delete(arr_2d,3)
c

[[  0   1  22]
 [  3   4   5]
 [  6   7 100]]


array([  0,   1,  22,   4,   5,   6,   7, 100])

**Q3.a. Create a 2D array. Iterate through the elements of the array and print elements using both nditer() and for loop.**


In [60]:
arr_3=np.random.randint(100,size=(3,3))
#prints the elements in the row wise
for i in arr_3:
    print(i)

[73 31 44]
[73 34 28]
[79 72 65]


In [62]:
for i in arr_3:
    for j in  i:
        print(j)

73
31
44
73
34
28
79
72
65


In [64]:
# To access every element we have to use another for loop
for i in arr_3:
    for j in  i:
        print(j,end=" ")
    print()

73 31 44 
73 34 28 
79 72 65 


In [66]:
#to print index and element
for i,j in np.ndenumerate(arr_3):
    print(i,j)


(0, 0) 73
(0, 1) 31
(0, 2) 44
(1, 0) 73
(1, 1) 34
(1, 2) 28
(2, 0) 79
(2, 1) 72
(2, 2) 65


In [161]:
#prints elements in row wise
for i in np.nditer(arr_3):
    print(i)

13
4
30
28
13
2
1
27
23


In [179]:
#prits every elements in row wise
for i in np.nditer(arr_3):
    print(i)

13
4
30
28
13
2
1
27
23


**b. Generate two arrays with random float elements in it.**

**-perform all python operations("*" + - / % //).**

**- Also apply all mathematical functions on the two arrays**

In [712]:
a=np.random.rand(3,3)
b=np.random.rand(3,3)
print(a)
print()
print(b)

[[0.14781876 0.56126317 0.28260707]
 [0.60330054 0.74592181 0.80283431]
 [0.31504438 0.19713987 0.33905859]]

[[0.85329785 0.61799098 0.61460607]
 [0.20601985 0.12277918 0.07753033]
 [0.39359741 0.00206054 0.5845483 ]]


In [265]:
#multiplication
print(np.multiply(a,b))
print()
print(a*b)

[[0.02068251 0.00626875 0.34277171]
 [0.02962767 0.16993985 0.09975256]
 [0.65404177 0.43086245 0.06013546]]

[[0.02068251 0.00626875 0.34277171]
 [0.02962767 0.16993985 0.09975256]
 [0.65404177 0.43086245 0.06013546]]


In [269]:
#suntraction
print(np.subtract(a,b))
print()
print(a-b)

[[ 0.57146184  0.21431363 -0.40746198]
 [-0.49813036  0.59552521  0.52522225]
 [ 0.25738278  0.52053919  0.22968483]]

[[ 0.57146184  0.21431363 -0.40746198]
 [-0.49813036  0.59552521  0.52522225]
 [ 0.25738278  0.52053919  0.22968483]]


In [273]:
#division
print(np.divide(a,b))
print()
print(a/b)

[[17.73320936  9.21839904  0.50528674]
 [ 0.09729734  3.82551373  4.54542545]
 [ 1.37290379  2.16752493  2.47288551]]

[[17.73320936  9.21839904  0.50528674]
 [ 0.09729734  3.82551373  4.54542545]
 [ 1.37290379  2.16752493  2.47288551]]


In [275]:
#addition
print(np.add(a,b))
print()
print(a+b)

[[0.63976456 0.26646822 1.23980326]
 [0.60551181 1.01705932 0.82150391]
 [1.63780737 1.41223611 0.54156898]]

[[0.63976456 0.26646822 1.23980326]
 [0.60551181 1.01705932 0.82150391]
 [1.63780737 1.41223611 0.54156898]]


In [281]:
#floor division
print(np.floor_divide(a,b))
print()
print(a//b)

[[17.  9.  0.]
 [ 0.  3.  4.]
 [ 1.  2.  2.]]

[[17.  9.  0.]
 [ 0.  3.  4.]
 [ 1.  2.  2.]]


In [283]:
#remainder
print(np.remainder(a,b))
print()
print(a%b)

[[0.0250401  0.00569526 0.41617064]
 [0.05369072 0.1739911  0.08079978]
 [0.25738278 0.07469073 0.07374275]]

[[0.0250401  0.00569526 0.41617064]
 [0.05369072 0.1739911  0.08079978]
 [0.25738278 0.07469073 0.07374275]]


In [307]:
#sum
print(np.sum(a)) #sum of all elements
print(np.sum(a,axis=0)) #col wise sum
print(np.sum(a,axis=1)) #row wise sum

5.095130464979675
[1.606899   2.01307084 1.47516062]
[1.26217477 1.53334607 2.29960963]


In [675]:
print("total sum")
print(np.sum(a)+np.sum(b)) #total sum
print("row wise sum")
print(np.sum(a,axis=0)+np.sum(a,axis=0)) #col wise sum
print("col wise sum")
print(np.sum(a,axis=1)) #row wise sum

total sum
8.818060653335204
row wise sum
[1.68452377 3.72582143 2.56370217]
col wise sum
[0.78128028 1.66790916 1.53783424]


In [585]:
#matrix multiplication
print(np.matmul(a,b))

[[0.81269546 0.59077497 0.73888067]
 [0.60639489 0.69655919 0.77450616]
 [0.43028423 0.71289234 0.77955115]]


In [587]:
#multiplication multiplication using @ 
print(a @ b)

[[0.81269546 0.59077497 0.73888067]
 [0.60639489 0.69655919 0.77450616]
 [0.43028423 0.71289234 0.77955115]]


In [657]:
#dot
print(np.dot(a,b))

[[2.87660624 2.83152863 3.83189452]
 [1.70577954 2.74570117 3.31940246]
 [2.0701373  2.3254075  3.06107818]]


In [661]:
#minimum
print(np.min(a))
print()
print(np.min(a,axis=0))
print()
print(np.min(a,axis=1))

0.04282639970724145

[0.0428264  0.19873833 0.55685309]

[0.0428264  0.19873833 0.14964336]


In [665]:
#maximum
print(np.max(a))
print()
print(np.max(a,axis=0))
print()
print(np.max(a,axis=1))

0.8158267503233232

[0.45992833 0.81582675 0.60579584]

[0.41074867 0.81582675 0.6363353 ]


In [653]:
#exponential
print(np.exp(a,b))

[[1.04375668 2.41367445 2.67813311]
 [1.91541444 1.21986272 1.74517196]
 [1.16141996 1.67824974 2.21236105]]


In [551]:
#transpose
a=np.arange(9).reshape(3,3)
b=np.arange(16).reshape(4,4)
print("====matrix a====")
print(a)
print("====transpose of a====")
print(a.T)
print("====matrix a====")
print(b)
print("=====transpose of b====")
print(b.T)

====matrix a====
[[0 1 2]
 [3 4 5]
 [6 7 8]]
====transpose of a====
[[0 3 6]
 [1 4 7]
 [2 5 8]]
====matrix a====
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
=====transpose of b====
[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [716]:
#sin
d=np.sin(a,b)
d

array([[0.14728104, 0.532256  , 0.27886025],
       [0.56736344, 0.67864914, 0.71932789],
       [0.30985867, 0.1958654 , 0.33259942]])

In [720]:
#cos
e=np.cos(a,b)
e

array([[0.98909469, 0.84658346, 0.96033169],
       [0.8234675 , 0.73446263, 0.69467071],
       [0.95078263, 0.98063079, 0.9430682 ]])

In [724]:
#sqrt
f=np.sqrt(a,b)
f

array([[0.38447206, 0.74917499, 0.531608  ],
       [0.77672423, 0.86366765, 0.89601022],
       [0.56128814, 0.44400436, 0.58228738]])

**Q3.4.Create a random NumPy array. Generate mean, mode, median, variance and standard deviation of that array.**

In [746]:
s=np.random.randint(10,size=(3,3))
print(s)

[[8 3 0]
 [5 6 1]
 [1 8 7]]


In [748]:
#mean

print("===total mean===")
print()
a=np.mean(s) #total mean
print(a)
print()
print("===col wise mean===")
print()
print(np.mean(s,axis=0))
print()
print("===row wise mean===")
print()
print(np.mean(s,axis=1))



===total mean===

4.333333333333333

===col wise mean===

[4.66666667 5.66666667 2.66666667]

===row wise mean===

[3.66666667 4.         5.33333333]


In [750]:
#mode-numpy has no attribute 'mode'
b=np.mode(s)

AttributeError: module 'numpy' has no attribute 'mode'

In [752]:
#median-
print(s)
c=np.median(s)
print("total median")
print(c)
print()
print("col wise median")
print(np.median(s,axis=0))
print()
print("row wise median")
print(np.median(s,axis=1))
print()


[[8 3 0]
 [5 6 1]
 [1 8 7]]
total median
5.0

col wise median
[5. 6. 1.]

row wise median
[3. 5. 7.]



In [762]:
#variance
f=np.var(a)
f

6.666666666666667

In [768]:
#standard deviation
g=np.std(a)
g

2.581988897471611

**b.Create two NumPy arrays of the same length with random numerical values. Compute the correlation coefficient between the two arrays**

In [822]:
x=np.random.randint(100,size=(3,3))
y=np.random.randint(50,size=(3,3))
z=np.corrcoef(x,y)
z

array([[ 1.        ,  0.85513825, -0.97323721, -0.02137846, -0.33229303,
        -0.51472745],
       [ 0.85513825,  1.        , -0.71312259,  0.5       , -0.77309904,
        -0.88461538],
       [-0.97323721, -0.71312259,  1.        ,  0.25055659,  0.10665542,
         0.30392959],
       [-0.02137846,  0.5       ,  0.25055659,  1.        , -0.93585673,
        -0.84615385],
       [-0.33229303, -0.77309904,  0.10665542, -0.93585673,  1.        ,
         0.97967611],
       [-0.51472745, -0.88461538,  0.30392959, -0.84615385,  0.97967611,
         1.        ]])